workflows:
  build-macos:
    name: Build MacOS
    environment:
      flutter: 3.32.4
      xcode: latest
      cocoapods: default
      groups:
        - mapiah_github_token

    triggering:
      events:
        - tag
      tag_patterns:
      - pattern: 'v[0-9]+.[0-9]+.[0-9]+'
        include: true

    scripts:
      - name: Get ´flutter pub´ dependencies
        script: |
          set -e
          flutter pub get

      - name: Enable MacOS build
        script: |
          set -e
          flutter config --enable-macos-desktop
          defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES

      - name: Build MacOS release
        script: |
          set -e
          flutter build macos --release

      - name: Create DMG
        script: |
          set -e
          brew install node
          npm install -g appdmg
          appdmg appdmg.json build/macos/Mapiah.dmg

    artifacts:
      - build/macos/Mapiah.dmg

    publishing:
      scripts:
      - name: Create GitHub Release with GH CLI
        script: |
          set -e
          # Store token in a different variable and unset GITHUB_TOKEN
          GH_TOKEN=$GITHUB_TOKEN
          unset GITHUB_TOKEN
          
          # Authenticate using the stored token
          gh auth login --with-token <<< "$GH_TOKEN"

          # Optionally, generate or copy your changelog
          # For example, if you have a changelog.md already:
          # cp path/to/your/changelog.md changelog.md

          # Manually setting CM_TAG for debugging purposes
          # This should be set to the tag that triggered the workflow
          # CM_TAG=v0.2.4

          # Create the release
          gh release create "${CM_TAG}" \
            --title "Mapiah ${CM_TAG}" \
            --notes "Release ${CM_TAG}" \
            build/macos/Mapiah.dmg
