workflows:
  build-macos:
    name: Build macOS Universal
    environment:
      flutter: 3.32.4
      xcode: latest
      cocoapods: default
      # vars:
      #   GITHUB_TOKEN: Encrypted(...) # Você criará esse secret no painel do Codemagic
      groups:
        - mapiah_github_token

    triggering:
      events:
        - tag
      tag_patterns:
        - include: true
        - pattern:
            'v[0-9]+.[0-9]+.[0-9]+'

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Enable universal macOS build
        script: |
          flutter config --enable-macos-desktop
          defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES

      - name: Build macOS
        script: flutter build macos --release

      - name: Create DMG
        script: |
          brew install node
          npm install -g appdmg
          appdmg appdmg.json build/macos/Mapiah.dmg

    artifacts:
      - build/macos/Mapiah.dmg

    publishing:
      scripts:
      - name: Create GitHub Release with GH CLI
        script: |
          # Set up GitHub CLI authentication
          echo "$GITHUB_TOKEN" | gh auth login --with-token

          # Optionally, generate or copy your changelog
          # For example, if you have a changelog.md already:
          # cp path/to/your/changelog.md changelog.md

          # Create the release
          gh release create "$FCI_TAG" \
            --title "Mapiah $FCI_TAG" \
            build/macos/Mapiah.dmg

