name: mapiah
description: Graphical interface for Therion cave mapping software written in Flutter.
version: 0.0.2+2
homepage: https://mapiah.org
repository: https://github.com/rsevero/mapiah.git
issue_tracker: https://github.com/rsevero/mapiah/issues

environment:
  sdk: '>=3.1.5 <4.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  charset: ^2.0.0
  dart_mappable: ^4.3.0
  dart_numerics: ^0.0.6
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.0
  get_it: ^8.0.3
  intl: any
  intl_utils: ^2.8.7
  meta: ^1.0.0
  mobx: ^2.0.0
  open_file: ^3.0.0
  package_info_plus: ^8.0.0
  path_provider: ^2.0.0
  petitparser: ^6.0.0
  toml: ^0.16.0

dev_dependencies:
  build_runner: ^2.0.0
  dart_mappable_builder: ^4.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.0
  test: ^1.0.0

flutter:
  uses-material-design: true
