name: mapiah
description: Graphical interface for Therion cave mapping software written in Flutter.
version: 0.0.1+1
homepage: https://mapiah.org
repository: https://github.com/rsevero/mapiah.git
issue_tracker: https://github.com/rsevero/mapiah/issues

environment:
  sdk: '>=3.1.5 <4.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  charset: ^2.0.1
  dart_mappable: ^4.3.0
  dart_numerics: ^0.0.6
  file_picker: ^8.1.6
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  get: ^4.6.1
  intl: ^0.20.1
  meta: ^1.9.1
  mobx: ^2.5.0
  open_file: ^3.3.2
  package_info_plus: ^8.1.2
  path_provider: ^2.1.1
  petitparser: ^6.0.1
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.0
  test: null

flutter:
  uses-material-design: true
