name: mapiah
description: Graphical interface for Therion cave mapping software written in Flutter.
version: 0.0.2+2
homepage: https://mapiah.org
repository: https://github.com/rsevero/mapiah.git
issue_tracker: https://github.com/rsevero/mapiah/issues

environment:
  sdk: '>=3.1.5 <4.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  charset: ^2.0.0
  collection: ^1.19.0
  dart_numerics: ^0.0.6
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.0
  intl: any
  intl_utils: ^2.8.7
  logger: ^2.5.0
  meta: ^1.0.0
  mobx: ^2.0.0
  open_file: ^3.0.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_drawing: ^1.0.1
  path_provider: ^2.0.0
  petitparser: ^6.0.0
  toml: ^0.16.0
  window_size: ^0.1.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.0
  test: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/change-scrap-tool.png
    - assets/icons/select-tool.png
    - assets/icons/zoom_minus.png
    - assets/icons/zoom_one_to_one.png
    - assets/icons/zoom-out-scrap.png
    - assets/icons/zoom_plus_minus.png
    - assets/icons/zoom_plus.png
    - assets/icons/zoom_selection.png

