name: mapiah
description: Graphical interface for Therion cave mapping software written in Flutter.
version: 0.0.1+1
repository: https://github.com/rsevero/mapiah.git

environment:
  sdk: '>=3.1.5 <4.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  charset: ^2.0.1
  dart_numerics: ^0.0.6
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  get: ^4.6.1
  intl: ^0.18.1
  meta: ^1.9.1
  open_file: ^3.3.2
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  petitparser: ^6.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: null

dependency_overrides:
  test_api: 0.6.1

flutter:
  uses-material-design: true
