name: Build Windows release of Mapiah
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Simulated tag for testing'
        required: false
        default: 'v1.0.0-test'

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Determine tag
        id: determine-tag
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # Only validate format for automatic tag pushes
            TAG=${GITHUB_REF#refs/tags/}
            if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "::error::Invalid tag format: $TAG (must match vX.Y.Z)"
              exit 1
            fi
          else
            # For workflow_dispatch, use input directly
            TAG="${{ github.event.inputs.test_tag }}"
          fi
          echo "TAG_NAME=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      - name: Debug output
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Using tag: ${{ steps.determine-tag.outputs.TAG_NAME }}"

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.determine-tag.outputs.TAG_NAME }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4

      - run: flutter --version
