name: Build Windows release of Mapiah
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Simulated tag for testing'
        required: false
        default: 'v1.0.0-test'

jobs:
  main:
    runs-on: windows-latest
    steps:
      # Only validate tag format for automatic runs
      - name: Validate tag (automatic runs only)
        if: github.event_name == 'push'
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid tag format: $TAG (must match vX.Y.Z)"
            exit 1
          fi
          echo "Validated tag: $TAG"
        shell: bash

      - name: Debug checkout information
        run: |
          echo "Trigger type: ${{ github.event_name }}"
          echo "Checked out SHA: ${{ github.sha }}"
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Using tag: ${GITHUB_REF#refs/tags/}"
          else
            echo "Using latest commit"
          fi

      # Smart checkout - uses tag only for automatic runs
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'push' && github.ref || '' }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4

      - run: flutter --version
